- name: Install Nginx on Ubuntu 22.04
  hosts: all
  become: yes
  vars:
    nginx_version: "1.18.0-6ubuntu14.6"

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
    
    - name: Install Nginx
      apt:
        name: "nginx={{ nginx_version }}"
        state: present

    - name: Start Nginx service
      service:
        name: nginx
        state: started