---
- name: Install Micronaut on Ubuntu 22.04
  hosts: all
  vars:
    micronaut_version: "4.7.6"
    jdk_version: "21"

  tasks:
    - name: Update APT package index
      apt:
        update_cache: yes
      become: yes

    - name: "Install JDK {{ jdk_version }}"
      apt:
        name: "openjdk-{{ jdk_version }}-jdk"
        state: present
      become: yes
    
    - name: Install unzip
      apt:
        name: unzip
        state: present
      become: yes

    - name: Check if Micronaut CLI is already installed
      stat:
        path: /usr/local/bin/micronaut-cli
      register: micronaut_cli_check

    - name: Install Micronaut CLI if not installed
      when: not micronaut_cli_check.stat.exists
      block:
        - name: Download Micronaut CLI
          get_url:
            url: "https://github.com/micronaut-projects/micronaut-starter/releases/download/v{{ micronaut_version }}/micronaut-cli-{{ micronaut_version }}.zip"
            dest: /tmp/micronaut-cli.zip
          become: no

        - name: Unzip Micronaut CLI
          unarchive:
            src: /tmp/micronaut-cli.zip
            dest: /usr/local/bin/
            remote_src: yes
          become: yes

        - name: Rename the extracted directory
          command: mv /usr/local/bin/micronaut-cli-{{ micronaut_version }} /usr/local/bin/micronaut-cli
          become: yes

        - name: Clean up
          file:
            path: /tmp/micronaut-cli.zip
            state: absent
    
    - name: Set environment variables for Micronaut
      copy:
        content: |
          export MICRONAUT_HOME="/usr/local/bin/micronaut-cli"
          export PATH="$MICRONAUT_HOME/bin:$PATH"
        dest: /etc/profile.d/micronaut.sh
        mode: '0755'
      become: yes

    - name: Validate Micronaut CLI installation
      shell:
        cmd: |
          source /etc/profile.d/micronaut.sh
          mn --version
        executable: /bin/bash
      register: micronaut_version_output
      failed_when: micronaut_version_output.rc != 0
