---
- name: Install and Configure MongoDB on Ubuntu 22.04
  hosts: all
  become: yes
  vars:
    mongo_version: "8.0"
    mongo_minor_version: "8.0.4"

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Import MongoDB GPG key
      apt_key:
        url: "https://www.mongodb.org/static/pgp/server-{{ mongo_version }}.asc"
        state: present

    - name: Add MongoDB repository
      apt_repository:
        filename: "/etc/apt/sources.list.d/mongodb-org-{{ mongo_version }}.list"
        repo: "deb https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/{{ mongo_version }} multiverse"
        state: present
        update_cache: yes

    - name: Install MongoDB
      apt:
        name: "mongodb-org={{ mongo_minor_version }}"
        state: present
        update_cache: yes

    - name: Start and enable MongoDB service
      systemd:
        name: mongod
        state: started
        enabled: yes
